---
title: "Tidying Data in R"
author: "Robert Orttung"
date: "August 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F, message = F}
library(dplyr)
library(tidyr)
```
Read in data from Mike Byerly. 2016. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.


```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)

```

%>%   command shift m key word shortcut for the 

```{r}
catch_df <- catch_df %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>%
  gather(key = "species",value = "catch",-Region,-Year) %>%
  rename(catch_thousands = catch)
head(catch_df)
```

Reverse of gather is spread

Mutate

```{r}
catch_integers <- as.integer(catch_df$catch_thousands)

i = which(is.na(catch_integers) == T)

catch_df$catch_thousands[i]

```

need to turn i into 1 in the Thousands column
coerce catch_thousands into integer type
convert catch_thousands to catch

```{r}
catch_df <- catch_df %>% 
  mutate(catch_thousands = ifelse(catch_thousands == "i", 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.integer(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000)
tail(catch_df)

```









